<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE definition [
	<!ELEMENT definition (version, xml_path, entry+)>
	<!ELEMENT version        (#PCDATA)>
	<!ELEMENT xml_version    (#PCDATA)>

        <!ELEMENT entry          (content_path, content_type, content, item+)>
	<!ELEMENT content_path   (#PCDATA)>
	<!ELEMENT content_type   (#PCDATA)>
	<!ELEMENT content        (#PCDATA)>

        <!ELEMENT item           (name, data_path, data_type, data_value)>
        <!ELEMENT name		 (#PCDATA)>
	<!ELEMENT data_path      (#PCDATA)>
	<!ELEMENT data_type      (#PCDATA)>
	<!ELEMENT data_value     (#PCDATA)>
]>

<definition>
<version>2.5</version>
<entry>
	<content_path>/proc/fs/lustre/osd-ldiskfs/lustre-MDT0000/quota_slave/acct_user</content_path>
	<content_type>external</content_type>
	<content>mdt_acctuser.data</content>
	<item>
		<name>mdt_acctuser</name>
		<data_path>${hostname}/lustre-MDT0000-acctuser_0/derive-usage_inodes.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>238</data_value>
	</item>
	<item>
		<name>mdt_acctuser</name>
		<data_path>${hostname}/lustre-MDT0000-acctuser_0/derive-usage_kbytes.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>1388</data_value>
	</item>
	<item>
		<name>mdt_acctuser</name>
		<data_path>${hostname}/lustre-MDT0000-acctuser_500/derive-usage_inodes.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>2</data_value>
	</item>
	<item>
		<name>mdt_acctuser</name>
		<data_path>${hostname}/lustre-MDT0000-acctuser_500/derive-usage_kbytes.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>0</data_value>
	</item>
</entry>
</definition>
