<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE definition [
	<!ELEMENT definition (version, xml_path, entry+)>
	<!ELEMENT version        (#PCDATA)>
	<!ELEMENT xml_version    (#PCDATA)>

        <!ELEMENT entry          (content_path, content_type, content, item+)>
	<!ELEMENT content_path   (#PCDATA)>
	<!ELEMENT content_type   (#PCDATA)>
	<!ELEMENT content        (#PCDATA)>

        <!ELEMENT item           (name, data_path, data_type, data_value)>
        <!ELEMENT name		 (#PCDATA)>
	<!ELEMENT data_path      (#PCDATA)>
	<!ELEMENT data_type      (#PCDATA)>
	<!ELEMENT data_value     (#PCDATA)>
]>

<definition>
<version>2.5</version>
<entry>
	<content_path>/proc/fs/lustre/mdt/lustre-MDT0000/md_stats</content_path>
	<content_type>external</content_type>
	<content>md_stats.data</content>
	<item>
		<name>md_stats_open</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-open.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>1303</data_value>
	</item>
	<item>
		<name>md_stats_close</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-close.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>1108</data_value>
	</item>
	<item>
		<name>md_stats_mknod</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-mknod.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>4</data_value>
	</item>
	<item>
		<name>md_stats_link</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-link.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>2</data_value>
	</item>
	<item>
		<name>md_stats_unlink</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-unlink.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>1111111</data_value>
	</item>
	<item>
		<name>md_stats_mkdir</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-mkdir.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>53</data_value>
	</item>
	<item>
		<name>md_stats_rmdir</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-rmdir.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>33</data_value>
	</item>
	<item>
		<name>md_stats_rename</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-rename.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>42</data_value>
	</item>
	<item>
		<name>md_stats_getattr</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-getattr.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>1607</data_value>
	</item>
	<item>
		<name>md_stats_setattr</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-setattr.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>61</data_value>
	</item>
	<item>
		<name>md_stats_getxattr</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-getxattr.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>33</data_value>
	</item>
	<item>
		<name>md_stats_setxattr</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-setxattr.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>1</data_value>
	</item>
	<item>
		<name>md_stats_statfs</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-statfs.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>31</data_value>
	</item>
	<item>
		<name>md_stats_sync</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-sync.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>4</data_value>
	</item>
	<item>
		<name>md_stats_samedir_rename</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-samedir_rename.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>42</data_value>
	</item>
	<item>
		<name>md_stats_crossdir_rename</name>
		<data_path>${hostname}/lustre-MDT0000-md_stats/derive-crossdir_rename.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>11</data_value>
	</item>
</entry>
</definition>
