<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE definition [
	<!ELEMENT definition (version, xml_path, entry+)>
	<!ELEMENT version        (#PCDATA)>
	<!ELEMENT xml_version    (#PCDATA)>

        <!ELEMENT entry          (content_path, content_type, content, item+)>
	<!ELEMENT content_path   (#PCDATA)>
	<!ELEMENT content_type   (#PCDATA)>
	<!ELEMENT content        (#PCDATA)>

        <!ELEMENT item           (name, data_path, data_type, data_value)>
        <!ELEMENT name		 (#PCDATA)>
	<!ELEMENT data_path      (#PCDATA)>
	<!ELEMENT data_type      (#PCDATA)>
	<!ELEMENT data_value     (#PCDATA)>
]>

<definition>
<version>2.5</version>
<entry>
	<content_path>/proc/fs/lustre/lod/testfs-MDT0000-mdtlov/filesused</content_path>
	<content_type>external</content_type>
	<content>filesused.data</content>
	<item>
		<name>mdt_filesused</name>
		<data_path>${hostname}/testfs-MDT0000-filesinfo/gauge-filesused.rrd</data_path>
		<data_type>derive</data_type>
		<data_value>238</data_value>
	</item>
</entry>
</definition>
